# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml

#import dracula.draw

# Load existing settings made via :set
config.load_autoconfig()

#dracula.draw.blood(c, {
#    'spacing': {
#        'vertical': 6,
#        'horizontal': 8
#    }
#})
config.bind('<Ctrl-/>', 'spawn --userscript qute-pass')
config.bind('<Ctrl-p>', 'spawn --userscript qute-pass -w')

#config.load_autoconfig()
config.source('themes/onedark.py')
