# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/.local/bin:$PATH
export PATH="$PATH:/opt/nvim-linux64/bin"
export DENO_INSTALL="/home/hudamnhd/.deno"
# export PATH=$PATH:$HOME/.local/bin/helix:/
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH=$HOME/.fzf_browser:$PATH
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"



# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
git
forgit
)

source $ZSH/oh-my-zsh.sh

#zsh-autosuggestions
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi
export PATH="/usr/local/bin:$PATH"


# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ta='tmux attach -t'
alias fd='fdfind'
alias tl='tmux list-sessions'
alias ts='tmux new-session -A -D -s'
alias duh='du -d 1 -h'
alias gsed='sed'
# Set up fzf key bindings and fuzzy completion

# export FZF_DEFAULT_COMMAND="fdfind --type f"
export EDITOR='nvim'
export TERMINAL='alacritty'
export FZF_DEFAULT_COMMAND='fdfind --type f --type d'
export FZF_DEFAULT_OPTS="
    --layout=reverse
    --border
    --preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
    --bind 'ctrl-d:+reload(fdfind --type d)','ctrl-d:+change-preview(tree -C {})','ctrl-f:+change-preview(bat --style=numbers,changes --wrap never --color always {})','ctrl-f:+reload(fdfind --type f --follow -E .git --ignore-file ~/.gitignore)'
    --bind 'ctrl-e:preview-down','ctrl-b:preview-up'
    --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8
    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc
    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8
"
# --color=fg:#d8dee9,bg:#343d46,spinner:#ffcb6b,header:#5fb4b4,fg+:#d8dee9,hl+:#ffcb6b,bg+:#46505b,hl:#ffcb6b,border:#939393,gutter:#343d46,marker:#ffcb6b,prompt:#7aabdc,info:#ffcb6b
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden:wrap --bind '/:toggle-preview'"
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

source ~/.fzf-tab-completion/shell/zsh/completion.zsh
source ~/.fzf-tab-completion/shell/zsh/key-bindings.zsh
source ~/.fzf-tab-completion/shell/zsh/fzf-zsh-completion.sh
source ~/.fzf_browser/zsh_widgets.zsh
bindkey '^I' fzf_completion


function fzf-run-cmd-from-history() {
    local selected_command
    selected_command=$(history |  awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }' | awk '!x[$0]++' | fzf --cycle --tac --no-sort --preview 'echo {}' --preview-window down:10% --no-height --layout=reverse --border  --color=border:#82aaff --color=fg:#b1b6d2,bg:#222436,hl:#ffcc77 --color=fg+:#d6deeb,bg+:#1d3b53,hl+:#ffcc77 --color=info:#9ece6a,prompt:#ff5874,pointer:#82aaff --color=marker:#9ece6a,spinner:#af5fff,header:#9ece6a)

    if [[ -n "$selected_command" ]]; then
        eval "$selected_command"
    fi
}

zle -N fzf-run-cmd-from-history
bindkey '^[r' fzf-run-cmd-from-history
bindkey "^b" _fuzzybrowse_zsh_insert_output

function run_cmd_asynctask {
  zle reset-prompt
  asynctask -f
}
zle -N run_cmd_asynctask
bindkey "^[t" run_cmd_asynctask

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion



source /home/hudamnhd/.config/broot/launcher/bash/br

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
