return {
  "Konfekt/vim-CtrlXA",
  event = "VeryLazy",
  config = function()
    vim.cmd([[
    let g:CtrlXA_Toggles = [
    \ ['!=', '==' ],
    \ ['true', 'false' ],
    \ ['yes', 'no' ],
    \ ['on', 'off' ],
    \ ['enabled', 'disabled' ],
    \ ['active', 'inactive' ],
    \ ['start', 'stop' ],
    \ ['up', 'down' ],
    \ ['left', 'right' ],
    \ ['open', 'close' ],
    \ ['visible', 'hidden' ],
    \ ['expand', 'collapse' ],
    \ ['show', 'hide' ],
    \ ['add', 'remove' ],
    \ ['increase', 'decrease' ],
    \ ['include', 'exclude' ],
    \ ['allow', 'deny' ],
    \ ['accept', 'reject' ],
    \ ['positive', 'negative' ],
    \ ['front', 'back' ],
    \ ['forward', 'backward' ],
    \ ['light', 'dark' ],
    \ ['day', 'night' ],
    \ ['start', 'end' ],
    \ ['minimum', 'maximum' ],
    \ ['first', 'last' ],
    \ ['beginning', 'end' ],
    \ ['high', 'low' ],
    \ ['empty', 'full' ],
    \ ['clean', 'dirty' ],
    \ ['above', 'below' ],
    \ ['before', 'after' ],
    \ ['next', 'previous' ],
    \ ['increase', 'decrease' ],
    \ ['push', 'pull' ],
    \ ['win', 'lose' ],
    \ ['active', 'inactive' ],
    \ ['positive', 'negative' ],
    \ ['input', 'output' ],
    \ ['success', 'failure' ],
    \ ['accept', 'decline' ],
    \ ['include', 'exclude' ],
    \ ['pass', 'fail' ],
    \ ['hot', 'cold' ],
    \ ['big', 'small' ],
    \ ['in', 'out' ],
    \ ['front', 'back' ],
    \ ['left', 'right' ],
    \ ['up', 'down' ],
    \ ['enter', 'exit' ],
    \ ['start', 'stop', 'end' ],
    \ ['show', 'hide' ],
    \ ['add', 'remove' ],
    \ ['open', 'close' ],
    \ ['top', 'bottom' ],
    \ ['yes', 'no' ],
    \ ['active', 'inactive' ],
    \ ['enable', 'disable' ],
    \ ['visible', 'hidden' ],
    \ ['on', 'off' ],
    \ ['pick', 'fixup'],
    \ ] + g:CtrlXA_Toggles
]])
  end,
}
