-- local uv = vim.uv or vim.loop
-- local is_windows = uv.os_uname().version:match("Windows")
-- local sep = is_windows and "\\" or "/"

return {
  -- {
  --   "stevearc/three.nvim",
  --   -- commit = "713e20011f670e1209d51bdce46c740a774fa42c",
  --   event = "VeryLazy",
  --   opts = {
  --     bufferline = {
  --       events = { "BufReadPost", "BufWinLeave" },
  --       should_display = function(tabpage, bufnr, ts)
  --         return vim.bo[bufnr].buflisted or vim.bo[bufnr].modified
  --       end,
  --       -- should_display = function(tabpage, bufnr, ts)
  --       --   return vim.bo[bufnr].modified
  --       -- end,
  --       -- recency_slots = 9,
  --       -- enabled = true,
  --       icon = {
  --         dividers = { "▍", "" },
  --         scroll = { "«", "»" },
  --         pin_divider = "",
  --         pin = "󰐃",
  --       },
  --     },
  --     windows = {
  --       enabled = false,
  --       -- Constant or function to calculate the minimum window width of the focused window
  --       winwidth = function(winid)
  --         local bufnr = vim.api.nvim_win_get_buf(winid)
  --         return math.max(vim.bo[bufnr].textwidth, 80)
  --       end,
  --       -- Constant or function to calculate the minimum window height of the focused window
  --       winheight = 10,
  --     },
  --     projects = {
  --       allowlist = {
  --         vim.fn.stdpath("data") .. "/lazy",
  --         vim.fs.normalize("~/vimwiki"),
  --         vim.fs.normalize("~"),
  --       },
  --       autoadd = false,
  --       extra_allowlist = {},
  --     },
  --   },
  --   config = function(_, opts)
  --     vim.list_extend(opts.projects.allowlist, vim.tbl_keys(opts.projects.extra_allowlist))
  --     local three = require("three")
  --     three.setup(opts)
  --     -- stylua: ignore start
  --       vim.keymap.set("n", "<C-T>", three.prev, { noremap = true, desc = "Previous buffer" })
  --       vim.keymap.set("n", "<C-Y>", three.next, { noremap = true, desc = "Next buffer" })
  --
  --       -- vim.keymap.set("n", "<C-S-H>", three.wrap(three.prev, { delta = 100 }), { desc = "First buffer" })
  --
  --       vim.keymap.set("n", "gt", three.wrap(three.next_tab, { wrap = true }), { desc = "Goto next Tab" })
  --       vim.keymap.set("n", "gy", three.wrap(three.prev_tab, { wrap = true }), { desc = "Goto prev Tab" })
  --
  --     local keys = '123456789'
  --     for i = 1, #keys do
  --       local key = keys:sub(i,i)
  --       local key_combination = string.format('<space>%s', key)
  --       vim.keymap.set('n', key_combination, three.wrap(three.jump_to, i), { desc = "Goto buffer " .. i })
  --     end
  --     vim.keymap.set("n", "<space>`", three.wrap(three.next, { delta = 100 }), { desc = "Last buffer" })
  --
  --     local keys = '1234567890'
  --     for i = 1, #keys do
  --       local key = keys:sub(i,i)
  --       local key_combination = string.format('<space>bm%s', key)
  --       vim.keymap.set('n', key_combination, three.wrap(three.move_buffer, i), { desc = "move buffer " .. i })
  --     end
  --     vim.keymap.set("n", "<space>bm`", three.wrap(three.move_buffer, { delta = 100 }), { desc = "move last" })
  --
  --     vim.keymap.set("n", "<space>bh", three.hide_buffer, { desc = "[B]uffer [H]ide" })
  --     vim.keymap.set("n", "<space>bp", three.toggle_pin, { desc = "[B]uffer [P]in" })
  --     vim.keymap.set("n", "<space>tc", vim.cmd.tabclose, { desc = "Close tab" })
  --     vim.keymap.set("n", "<space>tb", three.clone_tab,     { desc = "Clone tab" })
  --     vim.keymap.set("n", "<space>tn", "<cmd>tabnew | set nobuflisted<CR>", { desc = "New tab" })
  --
  --       local function buff_del_all()
  --           local current_bufnr = vim.api.nvim_get_current_buf()
  --           local current_tabpage = vim.api.nvim_get_current_tabpage()
  --           local visible_buffers = {}
  --           local ts = three.get_tab_state(current_tabpage)
  --           for _, bufnr in ipairs(ts.buffers) do
  --             if bufnr ~= current_bufnr then
  --                 visible_buffers[bufnr] = true
  --             end
  --           end
  --
  --           for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
  --               if (vim.bo[bufnr].buflisted) and visible_buffers[bufnr] then
  --                   three.close_buffer(bufnr)
  --               end
  --           end
  --       end
  --
  --     vim.keymap.set("n", "<space>bd", three.smart_close, { desc = "smart_close" })
  --     vim.keymap.set("n", "<space>bw", three.close_buffer, { desc = "close_buffer" })
  --     vim.keymap.set("n", "<space>bq", buff_del_all, { desc = "delete all buff not current" })
  --
  --     local function project_add()
  --       local cwd = vim.loop.cwd()
  --       local project_path = vim.fn.fnamemodify(path, ":p:h")
  --       three.add_project(project_path)
  --       print("Adding project at path: " .. project_path)
  --     end
  --
  --
  --     vim.keymap.set("n", "<space>k", three.open_project, { desc = "Find Project" })
  --     vim.api.nvim_create_user_command("ProjectAdd", project_add, {})
  --     vim.api.nvim_create_user_command("ProjectDelete", function() three.remove_project() end, {})
  --
  --     vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#343D46", bg = "#D8DEE9" })
  --     vim.api.nvim_set_hl(0, "TabLineDividerSel", { fg = "#343D46", bg = "#D8DEE9" })
  --     vim.api.nvim_set_hl(0, "TabLineIndexSel", { fg = "#343D46", bg = "#D8DEE9" })
  --     vim.api.nvim_set_hl(0, "TabLine", { fg = "#eeeeee", bg = "#3d4751" })
  --     vim.api.nvim_set_hl(0, "TabLineDir", { fg = "#D8DEE9", bg = "#343D46" })
  --     vim.api.nvim_set_hl(0, "TabLineDivider", { fg = "#eeeeee", bg = "#3d4751" })
  --     vim.api.nvim_set_hl(0, "TabLineDividerVisible", { fg = "#eeeeee", bg = "#3d4751" })
  --     vim.api.nvim_set_hl(0, "TabLineFill", { fg = "#D8DEE9", bg = "#343D46" })
  --     vim.api.nvim_set_hl(0, "TabLineIndex", { fg = "#eeeeee", bg = "#3d4751" })
  --     vim.api.nvim_set_hl(0, "TabLineIndexVisible", { fg = "#343D46", bg = "#D8DEE9" })
  --     vim.api.nvim_set_hl(0, "TabLineScrollIndicator", { fg = "#eeeeee", bg = "#3d4751" })
  --     vim.api.nvim_set_hl(0, "TabLineVisible", { fg = "#343D46", bg = "#D8DEE9" })
  --     vim.api.nvim_set_hl(0, "TabLineModified", { bg = "#343D46", fg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineModifiedVisible", { bg = "#343D46", fg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineIndexModified", { bg = "#343D46", fg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineIndexModifiedVisible", { bg = "#343D46", fg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineDividerModified", { bg = "#343D46", fg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineDividerModifiedVisible", { fg = "#343D46", bg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineModifiedSel", { fg = "#343D46", bg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineIndexModifiedSel", { fg = "#343D46", bg = "#F9AE58" })
  --     vim.api.nvim_set_hl(0, "TabLineDividerModifiedSel", { fg = "#343D46", bg = "#F9AE58" })
  --     -- stylua: ignore end
  --   end,
  -- },
}
