return {
  "nguyenvukhang/nvim-toggler",
  event = "VeryLazy",
  config = function()
    -- init.lua
    require("nvim-toggler").setup({
      -- your own inverses
      inverses = {
        ["!="] = "==",
        ["true"] = "false",
        ["yes"] = "no",
        ["on"] = "off",
        ["enabled"] = "disabled",
        ["active"] = "inactive",
        ["start"] = "stop",
        ["up"] = "down",
        ["left"] = "right",
        ["open"] = "close",
        ["visible"] = "hidden",
        ["expand"] = "collapse",
        ["show"] = "hide",
        ["add"] = "remove",
        ["increase"] = "decrease",
        ["include"] = "exclude",
        ["allow"] = "deny",
        ["accept"] = "reject",
        ["positive"] = "negative",
        ["front"] = "back",
        ["forward"] = "backward",
        ["light"] = "dark",
        ["day"] = "night",
        ["start"] = "end",
        ["minimum"] = "maximum",
        ["first"] = "last",
        ["beginning"] = "end",
        ["high"] = "low",
        ["empty"] = "full",
        ["clean"] = "dirty",
        ["above"] = "below",
        ["before"] = "after",
        ["next"] = "previous",
        ["increase"] = "decrease",
        ["push"] = "pull",
        ["win"] = "lose",
        ["active"] = "inactive",
        ["positive"] = "negative",
        ["input"] = "output",
        ["success"] = "failure",
        ["accept"] = "decline",
        ["include"] = "exclude",
        ["pass"] = "fail",
        ["hot"] = "cold",
        ["big"] = "small",
        ["in"] = "out",
        ["front"] = "back",
        ["left"] = "right",
        ["up"] = "down",
        ["enter"] = "exit",
        ["start"] = "stop",
        ["show"] = "hide",
        ["add"] = "remove",
        ["open"] = "close",
        ["top"] = "bottom",
        ["yes"] = "no",
        ["active"] = "inactive",
        ["enable"] = "disable",
        ["visible"] = "hidden",
        ["on"] = "off",
      },
      -- removes the default <leader>i keymap
      remove_default_keybinds = true,
      -- removes the default set of inverses
      remove_default_inverses = true,
      -- auto-selects the longest match when there are multiple matches
      autoselect_longest_match = false,
    })
    -- Menetapkan keymap true 2
    vim.keymap.set("n", "<a-a>", function()
      require("nvim-toggler").toggle()
    end, { remap = true, silent = true })
  end,
}
