[file-run]
command="$(VIM_FILEPATH)"
command:c,cpp=$(+wrapper_cpp:) "$(VIM_PATHNOEXT)"
command:pascal="$(VIM_PATHNOEXT)"
command:go="$(VIM_PATHNOEXT)"
command:python=$(+python:python) "$(VIM_FILENAME)"
command:python/linux=$(+python:python3) "$(VIM_FILENAME)"
command:make=make -f "$(VIM_FILENAME)" run
command:javascript=node "$(VIM_FILENAME)"
command:typescript=deno run "$(VIM_FILENAME)"
command:sh=sh "$(VIM_FILENAME)"
command:lua=lua "$(VIM_FILENAME)"
command:perl=perl "$(VIM_FILENAME)"
command:ruby=ruby "$(VIM_FILENAME)"
command:zsh=zsh "$(VIM_FILENAME)"
command:bash=bash "$(VIM_FILENAME)"
command:fish=fish "$(VIM_FILENAME)"
command:php=php "$(VIM_FILENAME)"
command:scala=scala "$(VIM_FILENAME)"
command:haskell=runhaskell "$(VIM_FILENAME)"
command:applescript=osascript "$(VIM_FILENAME)"
command:vim=:source %|echo 'sourced ' . expand('%')
command:rust="$(VIM_PATHNOEXT)"
command:bxrc=bochs -q -f "$(VIM_FILENAME)"
command:odin=odin run "$(VIM_FILENAME)"
command:yacc="$(VIM_PATHNOEXT)"
command:html=:!!! brave-browser "$(VIM_FILEPATH)"
output=terminal
cwd=$(VIM_FILEDIR)
save=2

[md-preview]
command=mdpreview "$(VIM_CWD)" | echo "OPEN http://127.0.0.1:3000"
output=terminal
pos=floaterm
save=2

[project-build]
command=make
cwd=$(VIM_ROOT)
save=2

[project-run]
command=make run
cwd=$(VIM_ROOT)
output=terminal
save=2

[project-test]
command=make test
cwd=$(VIM_ROOT)
output=terminal
save=2

; [project-clean]
; command/linux=find . -type f -executable -delete
; cwd=$(VIM_ROOT)

; [git-user-proxy-on]
; command=git config --global http.proxy "socks5://127.0.0.1:1080" && git config --global https.proxy "socks5://127.0.0.1:1080"
;
; [git-user-proxy-off]
; command=git config --global --unset http.proxy && git config --global --unset https.proxy
;
; [git-local-proxy-on]
; command=git config --local http.proxy "socks5://127.0.0.1:1080" && git config --local https.proxy "socks5://127.0.0.1:1080"
;
; [git-local-proxy-off]
; command=git config --local --unset http.proxy && git config --local --unset https.proxy

[git-config-list]
command/win32=type .git\config
command=cat .git/config
cwd=<root>
errorformat=

[git-push]
command=git push
cwd=<root>
output=quickfix
pos=floaterm

[git-fetch]
command=git fetch
cwd=<root>
errorformat=

[git-pull]
command=git pull
cwd=<root>
output=quickfix
errorformat=

; [git-clean]
; command=git clean -f -d -x
; cwd=$(VIM_ROOT)
; output=terminal
; pos=quickfix

; [profile-switch]
; command=:AsyncTaskEnviron profile debug release

[async-stop]
command=:AsyncStop
notify=:echo "done"

[async-run]
command=:AsyncRun $(-name)
output=terminal

[yarn-project-build]
command=yarn build
cwd=<root>
output=quickfix
save=2

[yarn-project-test]
command=yarn test
cwd=<root>
output=raw
save=2

[yarn-project-dev]
command=yarn dev
cwd=<root>
output=terminal
pos=floaterm
save=2

[yarn-project-start]
command=yarn start
cwd=<root>
output=terminal
pos=floaterm
save=2

[yarn-project-install]
command=yarn install
cwd=<root>
output=terminal
save=2

[npm-project-build]
command=npm run build
cwd=<root>
output=quickfix
save=2

[npm-project-test]
command=npm run test
cwd=<root>
output=raw
save=2

[npm-project-dev]
command=npm run dev
cwd=<root>
output=terminal
pos=floaterm
save=2

[npm-project-start]
command=npm run start
cwd=<root>
output=terminal
pos=floaterm
save=2

[npm-project-install]
command=npm run install
cwd=<root>
output=raw
save=2

[php-artisan-serve]
command=php artisan serve
cwd=<root>
output=terminal
pos=floaterm
save=2

[php-artisan-dbwipe]
command=php artisan db:wipe
cwd=<root>
output=quickfix
save=2

[php-artisan-migrate]
command=php artisan migrate:refresh --seed
cwd=<root>
output=quickfix
save=2

[php-artisan-optimize]
command=php artisan optimize
cwd=<root>
output=quickfix
save=2

[vim-tutor]
command=cat ~/.config/nvim/vimtutor.txt
cwd=<root>

[regex-tutor]
command=cat ~/.config/nvim/panduan_regex_vim.md
cwd=<root>
